//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeCryptoEntities : DbContext
    {
        public DeCryptoEntities()
            : base("name=DeCryptoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountSet> AccountSet { get; set; }
        public virtual DbSet<BlueTeamSet> BlueTeamSet { get; set; }
        public virtual DbSet<FriendList> FriendList { get; set; }
        public virtual DbSet<GameSet> GameSet { get; set; }
        public virtual DbSet<RedTeamSet> RedTeamSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
    }
}
