//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendList
    {
        public string Account2_Nickname { get; set; }
        public string Account1_Nickname { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual AccountSet AccountSet { get; set; }
        public virtual AccountSet AccountSet1 { get; set; }
    }
}
