//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSet
    {
        public int GamesId { get; set; }
        public string WinnerTeam { get; set; }
        public string RoundNumber { get; set; }
        public int BlueTeam_BlueTeamId { get; set; }
        public int RedTeam_RedTeamId { get; set; }
    
        public virtual BlueTeamSet BlueTeamSet { get; set; }
        public virtual RedTeamSet RedTeamSet { get; set; }
    }
}
