//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSet
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string BirthDay { get; set; }
        public string Account_Nickname { get; set; }
    
        public virtual AccountSet AccountSet { get; set; }
    }
}
